### PR TITLE
fix(docker): replace tini with dumb-init

### PR DESCRIPTION
**Pull request by abester**
Replace tini with dumb-init  as the use TINI_SUBREAPER  is causing issues where  PR_SET_CHILD_SUBREAPER is unavailable on some  platforms.

### CODE REVIEW

**Comment by TelicentPaul** [comment]
@abester Should we make this change across the other Dockerfiles we have?

**Comment by rvesse** [comment]
@abester Do we have a write up of the underlying issue somewhere?  As @TelicentPaul notes we've used `tini` as the init process across pretty much all the platform containers so this will need fixing globally and it would be good to understand the problem so we aren't making the wrong fix and have to churn through another round of PRs

**Comment by abester** [comment]
> @abester Do we have a write up of the underlying issue somewhere? As @TelicentPaul notes we've used `tini` as the init process across pretty much all the platform containers so this will need fixing globally and it would be good to understand the problem so we aren't making the wrong fix and have to churn through another round of PRs

details of the problem: https://github.com/docker/for-mac/issues/6620#issuecomment-1694380189

its preventing the app from starting up when running in k8s on local desktop such as rancher-desktop , etc.

**Comment by abester** [comment]
> @abester Should we make this change across the other Dockerfiles we have?

I've done the PR for search, for now thats all that we need.

**Pull request merged**
